randomNumberGenerator.c
rc4ctx_t* rngContext
var - rngContext - The RC4 context state used for random number generation.
void rseed(U8 *key, int keylen, int isKeyHex)
rseed - Function used to create a random number generator object and set the seed for the random number generator.
key - uint8_t* - The key used to seed the random number generator. keylen - The length of the key key. isKeyHex - flag used to indicate if the key key is hex or ascii encoded.
References destroyRNG, constructRc4Context, rc4Init.
Referenced by main, constructRSAContext.
U8 rrand()
rrand - Function used to generate a random number of a single byte long.
U8 - A random number of 8 bits long.
References rc4GetByte.
Referenced by main, getPrime.
void destroyRNG()
destroyRNG - Function used to deallocate all memory allocated for the random number generator, specifically the RC4 key stream state context structure.
References destroyRc4Context.
Referenced by rseed, main, rsaClean.