rc4.c
const size_t RC4KEYLENGTH
Referenced by main.
int main(int argc, char *argv[])
References printHelp, rc4Test.outputFileName, rc4Test.keyFile, rsaKeyGenTester.key, mod.x, verifyArgument, clearMemory, RC4KEYLENGTH, constructRc4Context, rc4Init, performRc4, destroyRc4Context.
void printHelp()
printHelp - Function used to print the help menu for the rc4 utility
printHelp - Function used to print the help menu for the rsa kegen utilityprintHelp - Function used to print the help menu for the rsa encrypt utilityprintHelp - Function used to print the help menu for the rsa decrypt utility
Referenced by main, verifyArgument.
void clearMemory(unsigned char *inputFileName, unsigned char *outputFileName, unsigned char *keyFile, unsigned char *key)
clearMemory - Function used to deallocate all memory allocated for the rc4 utility.
clearMemory - Function used to deallocate all memory allocated for the rsa keygen utility.clearMemory - Function used to deallocate all memory allocated for the rsa encryption utility.clearMemory - Function used to deallocate all memory allocated for the rsa decryption utility.
Referenced by main.
void verifyArgument(size_t argCounter, size_t argc, char *parameter)
verifyArgument - Function used to verify if a paramter has an argument or not.
argCounter - The current index being verified for the commandline paramters. argc - The total number of commandline arguments. parameter - The parameter whose argument is being verified.
Referenced by main.