rc4Lib.c
rc4ctx_t* constructRc4Context()
constructRc4Context - Function to construct the RC4 context structure and construct the state vector used for RC4 byte generation. The user must use the function in order to initialize the RC4 state. The caller must also ensure that they use the member function destroyRc4Context in order to deallocate all memory once the RC4 structure is no longer needed.
rc4ctx_t* - a pointer to the rc4 context object created.
References mod.x, RC4_STATE_SIZE, rc4ctx_t::state, rc4ctx_t::index1, rc4ctx_t::index2.
Referenced by rseed, main.
void destroyRc4Context(rc4ctx_t *rc4Ctx)
destroyRc4Context - Function used to deallocate all memory allocated for the rc4 context structure passed in as
rc4Ctx. Sets the parameter rc4Ctx to NULL. rc4Ctx - The RC4 context structure to deallocate and clean.
Referenced by destroyRNG, main.
void rc4Init(rc4ctx_t *rc4Ctx, U8 *key, int keylen, uint8_t isKeyHex)
rc4Init - Function used to initialize the state of the RC4 context and the state vector used for the RC4 byte generate. Requires the use of the function constructRc4Context in order to generate a RC4 context. If the initialization key provided in
key is a hex string, it is converted to ascii string before initialization. rc4Ctx - rc4ctx_t* - a pointer to the RC4 context structure to initialize. key - uint8_t* - a pointer to the initialization key to be used. keylen - int - the length of the key provided key. isKeyHex - uint8_t - a flag to determine if the key passed in as key is a hex string or ascii string.
References keyHexToAscii, rsaKeyGenTester.key, rc4ctx_t::index1, RC4_STATE_SIZE, rc4ctx_t::state, rc4ctx_t::index2, swapStateElements.
Referenced by rseed, main.
uint8_t rc4GetByte(rc4ctx_t *rc4Ctx)
rc4GetByte - Function used to generate a single byte of the RC4 key stream for the RC4 context passed in as
rc4Ctx. Returns the single byte as a single uint8_t. rc4Ctx - rc4ctx_t* - a pointer to the RC4 context from which to generate the single byte. uint8_t - A single byte in the RC4 key stream.
References rc4ctx_t::index1, rc4ctx_t::index2, rc4ctx_t::state, swapStateElements.
Referenced by rrand, performRc4, print16Bytes.
void swapStateElements(U8 *val1, U8 *val2)
swapStateElements - Function to swap the contents of the uint8_t pointers passed in as parameters
val1 and val2. val1 - uint8_t* - pointer to a uint8_t variable whose contents to switch with val2. val2 - uint8_t* - pointer to a uint8_t variable whose contents to switch with val1.
References rc4Test.temp.
Referenced by rc4Init, rc4GetByte.
void performRc4(unsigned char *inputFileName, unsigned char *outputFileName, rc4ctx_t *rc4Ctx, int isTextHex)
performRc4 - Function used to encrypt or decrypt the contents of the file
inputFileName and write the result to the file outputFileName. The encryption or decryption is done using RC4 encryption or decryption. Each character in the input file is read in and a single byte for the RC4 key stream is generated. A single byte for the plaintext or Ciphertext and XOR'ed with a single byte from the RC4 key stream to generate a the corresponding ciphertext or plaintext. The bytes used during the RC4 encryption or decryption are generated from the RC4 context passed in as rc4Ctx. RC4 encryption inputFileName - unsigned char* - pointer to a string containing the path to the input file. outputFileName - unsigned char* - pointer to a string containing the path to the output file. rc4Ctx - rc4ctx_t* - a pointer to the RC4 context to use during encryption or decryption. isTextHex - flag used to determine if the input is encoded using ascii or hex encoding.
References hexToAsciiString, rc4GetByte, rc4Test.temp.
Referenced by main.