rsa.c
const int64_t CONSTANTE
Referenced by generateRsaKeys.
rsactx_t* constructRSAContext(unsigned char *initKey, uint8_t initKeyLength, int isKeyHex, int numBits)
constructRSAContext - Function used to construct the RSA context structure used for RSA key-pair generation. The function allocates all memory required. In addition, the function initializes the random number generator (RC4 key stream) using the key passed in as
initKey used for the generation of the RSA key-pairs. The function calls rsaInit function to aid in initialization. The caller must use cleanRSA in order to deallocate all memory once the key-pair has been generated. unsigned char* - initKey - The key used to initialize the random number generator. initKeyLength - uint8_t - The length of the key passed in as initKey. isKeyHex - int - a flag indicating whether the key initKey is a hex string or ascii encoded string. numBits - int - the number of bits required for the public and private RSA key pair to be generated. rsactx_t* - A pointer to the RSA context structure used to store the state of the RSA key generation.
References rsactx_t::initKey, rsactx_t::initKeyLength, rseed, rsactx_t::numBits, rsaInit.
Referenced by main.
void rsaInit(rsactx_t *rsaCtx)
rsaInit - Function used to initialize the RSA context state structure passed in as
rsaCtx. Used as a helper function for the constructRSAContext function. Does not need to be explicitly called by the user. Initializes all mpz library variables used as required. rsaCtx - rsactx_t* - A pointer to the RSA context state structure to initialize.
References rsactx_t::p, rsactx_t::q, rsactx_t::e, rsactx_t::d, rsactx_t::qn, rsactx_t::n, mod.x, rsactx_t::KU, rsactx_t::KR.
Referenced by constructRSAContext.
void generateRsaKeys(rsactx_t *rsaCtx)
generateRsaKeys - Function used to generate the RSA public and private key-pair according to the specifications within the RSA state passed in as
rsaCtx. Makes use of the mpz libraries in order to compute the prime numbers used for the p and q variables used during RSA key generation. The function does check for negative values for the "d" parameter as a result of under and overflows and makes the required adjustments. Stores the RSA key pair and the parameters used during RSA key generation in the RSA state structure. rsaCtx - rsactx_t* - The RSA context state to use for the RSA key-pair generation.
References getPrime, rsactx_t::p, rsactx_t::numBits, rsactx_t::q, rsactx_t::n, rsactx_t::qn, rsactx_t::e, CONSTANTE, rsactx_t::d, rsactx_t::KU, rsactx_t::KR.
Referenced by main.
void getPrime(mpz_t p, int bits)
getPrime - Function used to generate a prime number of length
bits and store it in p. Used for RSA key-pair generation. bits should be half the length of the total length of the key required for the RSA keys. The function generates bits - 1 random numbers using the RC4 random key stream generator and uses the LSB of each random number generated as a bit in the in the final prime number. Once the random number of bits length is generated, the mpz_nextprime is used to get the closest prime number to the random number generated and store it in p. p bits
References mod.x, rsaKeyGenTester.bits, rrand.
Referenced by generateRsaKeys.
void rsaEncrypt(unsigned char *outputFile, unsigned char *publicKeyFile, unsigned char *plainText, size_t isPlaintextHex)
rsaEncrypt - Function used to encrypt the plaintext passed in as
plainText using RSA encryption and write the resulting ciphertext to the file outputFile in decimal. Function treats the entire plainText as the a single decimal value and performs the RSA encryption. The function reads in the public key and writes the result to the output file. outputFile - unsigned char* - File to write the ciphertext to. publicKeyFile - unsigned char* - The file containing the public key to use during RSA encryption. The "n" paramter should be on the first line, followed by the newline character thereafter the "e" paramter should be placed in the public key file. plainText - unsigned char* - The plaintext to encrypt. isPlaintextHex - size_t - a flag used to indicate if the plaintext is encoded using ascii or hex encoding.
References test.n.
Referenced by main.
void rsaDecrypt(unsigned char *outputFile, unsigned char *privateKeyFile, unsigned char *cipherText)
rsaDecrypt - Function used to decrypt the ciphertext passed in as
cipherText using RSA decryption and write the resulting plaintext to the file outputFile as a string using ascii plaintext encoding. Function treats the entire cipherText as the a single decimal value and performs the RSA decryption. The function reads in the private key and writes the result to the output file. outputFile - unsigned char* - File to write the plaintext to. privateKeyFile - unsigned char* - The file containing the private key to use during RSA decryption. The "n" paramter should be on the first line, followed by the newline character thereafter the "d" paramter should be placed in the private key file. cipherText - unsigned char* - The ciphertext to decrypt.
References test.n.
Referenced by main.
void rsaWriteKeysToFile(rsactx_t *rsaCtx, unsigned char *publicKeyFileName, unsigned char *privateKeyFileName)
rsaWriteKeysToFile - Function used to write the public and private keys store in the RSA Context passed in as
rsaCtx to the publicKeyFileName and privateKeyFileName respectively. The RSA private and public keys are written to the files in accordance with the practical specification. With the n paramter followed by a newline character, followed by d/e and finally a newline character. rsaCtx - rsactx_t* - The RSA context containing the public and private key pair to be written. publicKeyFileName - unsigned char* - The file to write the RSA public key to. privateKeyFileName - unsigned char* - The file to write the RSA private key to.
References rsactx_t::KU, rsactx_t::KR.
Referenced by main.
void rsaClean(rsactx_t *rsaCtx)
rsaClean - Function used to deallocate all memory allocated for the RSA context state structure in
rsaCtx. In addition deallocates all memory used for the random number generator. rsaCtx - rsactx_t* - The RSA context state to deallocate.
References rsactx_t::p, rsactx_t::q, rsactx_t::e, rsactx_t::d, rsactx_t::qn, rsactx_t::n, mod.x, rsactx_t::KU, rsactx_t::KR, rsactx_t::initKey, rsactx_t::initKeyLength, destroyRNG, rsactx_t::numBits.
Referenced by main.