textConverter.c
uint8_t hexToInt(char ch)
hexToInt - Function that converts a given hex value into an integer.
ch - hex value that wil be converted to int. uint8_t the converted int value.
Referenced by hexToAscii.
uint8_t hexToAscii(char ch1, char ch2)
hexToAscii - Function that converts a given hex value to its ASCII equivalent.
ch1 - char value of the first hex value. ch2 - char value of the second hex value.
References hexToInt.
Referenced by hexToAsciiString.
void hexToAsciiString(char *hexString, char *asciiString, int hexStringLength)
hexToAsciiString - Function that converts a given string of hex values into its ASCII equivalent. A hex string contains hex chars and is "encoded" in ascii In order to encrypt it, it must be converted to the equivalent ascii plain text string plaintext string is half the size of hex, since two hex chars = 1 ascii char if hex string is "4A" it will be converted to "J" in ascii which will have a hex representation of "4a" The original hex string converted to hex staright or printed in hex straight rather will print or have the value "0x34", "0x31" BASICALLY THE HEX STRING FF IS INTERPRETED AS THE CHARS FF, whereas when using this function we intend it to be "J", ie the char "J"
char* hexString - The string of hex values to be converted. char* asciiString - The output of the converted hex string. int hexStringLength - The length of parameter hexString.
References mod.x, hexToAscii.
Referenced by performRc4, keyHexToAscii.
unsigned char* asciiToHexString(unsigned char *asciiString, unsigned char *hexString, size_t asciiStringLen)
Function name: asciiToHexString - convert an ascii String to an ascii string.
asciiString - unsigned char* pointing to the ASCII String to be converted. hexString - unsigned char* pointing to a memory where the converted Hex string should be stored. asciiStringLen - size_t containing the length of the ASCII String to be converted. unsigned char* asciiToHexString - pointer to the converted Hex String, pointing to the same memory location as hexString.
References mod.x.
unsigned char* keyHexToAscii(unsigned char *hexKey, int keyLength)
keyHexToAscii - Function to convert a hex encoded key to an ascii string. The caller must ensure they deallocate the memory allocated for the returned ascii encoded string.
hexKey - unsigned char* - the hexadecimal encoded key to convert. keyLength - int - the length of the key hexKey. unsigned char* - The resulting ascii encoded string.
References hexToAsciiString.
Referenced by rc4Init.