.TH "md_test_files__read_m_e" 3 "Thu May 23 2019" "Version 0.1" "EHN 410 - Group 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_test_files__read_m_eDEMO 1: 
 \- RSA keygen init: prac3EHN-410 Numbits: 128 RC4 RNG init: theTestKey34
.PP
.SH "DEMO 2: "
.PP
.PP
RC4 init: netsec410-2017 Numbits: 1024 RSA init: initRSAKey 
