.TH "mod.py" 3 "Thu May 23 2019" "Version 0.1" "EHN 410 - Group 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mod.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmod\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBx\fP = 495"
.br
.ti -1c
.RI "int \fBy\fP = 145"
.br
.ti -1c
.RI "int \fBz\fP = 841"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EHN 410 - Group 7 from the source code\&.
