.TH "rc4.h" 3 "Thu May 23 2019" "Version 0.1" "EHN 410 - Group 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc4.h
.SH SYNOPSIS
.br
.PP
\fC#include 'rc4Lib\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintHelp\fP ()"
.br
.RI "printHelp - Function used to print the help menu for the rc4 utility "
.ti -1c
.RI "void \fBclearMemory\fP (unsigned char *inputFileName, unsigned char *outputFileName, unsigned char *keyFile, unsigned char *key)"
.br
.RI "clearMemory - Function used to deallocate all memory allocated for the rc4 utility\&. "
.ti -1c
.RI "void \fBverifyArgument\fP (size_t argCounter, size_t argc, char *parameter)"
.br
.RI "verifyArgument - Function used to verify if a paramter has an argument or not\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const size_t \fBRC4KEYLENGTH\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Mohamed Ameen Omar (u16055323) 
.PP
Douglas Healy (u16018100) 
.PP
Llewellyn Moyse (u15100708) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2019-05-22
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2019 
.RE
.PP

.PP
Definition in file \fBrc4\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void clearMemory (unsigned char * publickeyfile, unsigned char * privatekeyfile, unsigned char * keyFile, unsigned char * key)"

.PP
clearMemory - Function used to deallocate all memory allocated for the rc4 utility\&. clearMemory - Function used to deallocate all memory allocated for the rc4 utility\&. 
.PP
Definition at line 165 of file rc4\&.c\&.
.SS "void printHelp ()"

.PP
printHelp - Function used to print the help menu for the rc4 utility printHelp - Function used to print the help menu for the rc4 utility 
.PP
Definition at line 148 of file rc4\&.c\&.
.SS "void verifyArgument (size_t argCounter, size_t argc, char * parameter)"

.PP
verifyArgument - Function used to verify if a paramter has an argument or not\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargCounter\fP - The current index being verified for the commandline paramters\&. 
.br
\fIargc\fP - The total number of commandline arguments\&. 
.br
\fIparameter\fP - The parameter whose argument is being verified\&. 
.RE
.PP

.PP
Definition at line 194 of file rc4\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const size_t RC4KEYLENGTH"

.PP
Definition at line 16 of file rc4\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EHN 410 - Group 7 from the source code\&.
