.TH "rc4ctx_t" 3 "Thu May 23 2019" "Version 0.1" "EHN 410 - Group 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc4ctx_t \- struct \fBrc4ctx_t\fP - Structure used to retain the context of the RC4 key stream generator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc4Lib\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBU8\fP \fBstate\fP [\fBRC4_STATE_SIZE\fP]"
.br
.ti -1c
.RI "uint16_t \fBindex1\fP"
.br
.ti -1c
.RI "uint16_t \fBindex2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct \fBrc4ctx_t\fP - Structure used to retain the context of the RC4 key stream generator\&. 
.PP
Definition at line 38 of file rc4Lib\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t index1"

.PP
Definition at line 40 of file rc4Lib\&.h\&.
.SS "uint16_t index2"

.PP
Definition at line 41 of file rc4Lib\&.h\&.
.SS "\fBU8\fP state[\fBRC4_STATE_SIZE\fP]"

.PP
Definition at line 39 of file rc4Lib\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EHN 410 - Group 7 from the source code\&.
