.TH "rc4LibTester.c" 3 "Thu May 23 2019" "Version 0.1" "EHN 410 - Group 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc4LibTester.c
.SH SYNOPSIS
.br
.PP
\fC#include 'rc4Lib\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint16Bytes\fP (\fBrc4ctx_t\fP *rc4Ctx)"
.br
.ti -1c
.RI "void \fBprintTestOutput\fP (\fBrc4ctx_t\fP *rc4Ctx)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthors:\fP
.RS 4
Mohamed Ameen Omar (u16055323) 
.PP
Douglas Healy (u16018100) 
.PP
Llewellyn Moyse (u15100708) 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2019-05-23
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2019 
.RE
.PP

.PP
Definition in file \fBrc4LibTester\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 39 of file rc4LibTester\&.c\&.
.SS "void print16Bytes (\fBrc4ctx_t\fP * rc4Ctx)"

.PP
Definition at line 16 of file rc4LibTester\&.c\&.
.SS "void printTestOutput (\fBrc4ctx_t\fP * rc4Ctx)"

.PP
Definition at line 26 of file rc4LibTester\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EHN 410 - Group 7 from the source code\&.
