.TH "rc4Test" 3 "Thu May 23 2019" "Version 0.1" "EHN 410 - Group 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc4Test
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBinputfileName\fP = 'temp'"
.br
.ti -1c
.RI "string \fBoutputFileName\fP = 'temp2'"
.br
.ti -1c
.RI "string \fBkeyFile\fP = ''"
.br
.ti -1c
.RI "\fBtemp\fP = subprocess\&.call(['\&./rc4','\-fi', inputfileName, '\-fo', outputFileName])"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string inputfileName = 'temp'"

.PP
Definition at line 10 of file rc4Test\&.py\&.
.SS "string keyFile = ''"

.PP
Definition at line 12 of file rc4Test\&.py\&.
.SS "string outputFileName = 'temp2'"

.PP
Definition at line 11 of file rc4Test\&.py\&.
.SS "temp = subprocess\&.call(['\&./rc4','\-fi', inputfileName, '\-fo', outputFileName])"

.PP
Definition at line 14 of file rc4Test\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EHN 410 - Group 7 from the source code\&.
