.TH "rsactx_t" 3 "Thu May 23 2019" "Version 0.1" "EHN 410 - Group 7" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rsactx_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rsa\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "mpz_t \fBp\fP"
.br
.ti -1c
.RI "mpz_t \fBq\fP"
.br
.ti -1c
.RI "mpz_t \fBe\fP"
.br
.ti -1c
.RI "mpz_t \fBd\fP"
.br
.ti -1c
.RI "mpz_t \fBqn\fP"
.br
.ti -1c
.RI "mpz_t \fBn\fP"
.br
.ti -1c
.RI "uint16_t \fBnumBits\fP"
.br
.ti -1c
.RI "unsigned char * \fBinitKey\fP"
.br
.ti -1c
.RI "uint8_t \fBinitKeyLength\fP"
.br
.ti -1c
.RI "mpz_t \fBKU\fP [2]"
.br
.ti -1c
.RI "mpz_t \fBKR\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file rsa\&.h\&.
.SH "Field Documentation"
.PP 
.SS "mpz_t d"

.PP
Definition at line 24 of file rsa\&.h\&.
.SS "mpz_t e"

.PP
Definition at line 23 of file rsa\&.h\&.
.SS "unsigned char* initKey"

.PP
Definition at line 28 of file rsa\&.h\&.
.SS "uint8_t initKeyLength"

.PP
Definition at line 29 of file rsa\&.h\&.
.SS "mpz_t KR[2]"

.PP
Definition at line 31 of file rsa\&.h\&.
.SS "mpz_t KU[2]"

.PP
Definition at line 30 of file rsa\&.h\&.
.SS "mpz_t n"

.PP
Definition at line 26 of file rsa\&.h\&.
.SS "uint16_t numBits"

.PP
Definition at line 27 of file rsa\&.h\&.
.SS "mpz_t p"

.PP
Definition at line 21 of file rsa\&.h\&.
.SS "mpz_t q"

.PP
Definition at line 22 of file rsa\&.h\&.
.SS "mpz_t qn"

.PP
Definition at line 25 of file rsa\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EHN 410 - Group 7 from the source code\&.
